/* Autogenerated with kurento-module-creator */

#ifndef __AR_MARKERDETECTOR_IMPL_HPP__
#define __AR_MARKERDETECTOR_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "ArMarkerdetector.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "ArMarkerdetectorOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace armarkerdetector
{
class ArMarkerdetectorImpl;
} /* armarkerdetector */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::armarkerdetector::ArMarkerdetectorImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
namespace module
{
namespace armarkerdetector
{
class ArThing;
} /* armarkerdetector */
} /* module */
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace armarkerdetector
{

class ArMarkerdetectorImpl : public OpenCVFilterImpl, public virtual ArMarkerdetector, public virtual ArMarkerdetectorOpenCVImpl
{

public:

  ArMarkerdetectorImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~ArMarkerdetectorImpl () {};

  void setPose (int id, int type, float value);
  void enableAugmentation (bool enable);
  void enableMarkerCountEvents (bool enable);
  void enableAugmentationSet (const std::vector<int> &arset);
  void disableAugmentationSet (const std::vector<int> &arset);
  void setArThing (const std::vector<std::shared_ptr<ArThing>> &arThing);
  void setMarkerPoseFrequency (bool enable, float frequency);
  void setMarkerPoseFrameFrequency (bool enable, int frequency);
  void setShowDebugLevel (int showDebugLevel);
  // TODO: Kludge, because ArMarkerdetectorOpenCVImpl is not inherited from Med\
  iaObject (?)
  virtual std::shared_ptr<MediaObject> getSharedFromThis() { 
    return shared_from_this(); 
  }

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* armarkerdetector */
} /* module */
} /* kurento */

#endif /*  __AR_MARKERDETECTOR_IMPL_HPP__ */
