/**
Licensing and distribution

ArModule is licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

ALVAR 2.0.0 - A Library for Virtual and Augmented Reality Copyright 2007-2012 VTT Technical Research Centre of Finland Licensed under the GNU Lesser General Public License

Irrlicht Engine, the zlib and libpng. The Irrlicht Engine is based in part on the work of the Independent JPEG Group The module utilizes IJG code when the Irrlicht engine is compiled with support for JPEG images.
*/

/** @author Markus Ylikerälä */

/* Autogenerated with kurento-module-creator */

#ifndef __AR_MARKERDETECTOR_IMPL_HPP__
#define __AR_MARKERDETECTOR_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "ArMarkerdetector.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "ArMarkerdetectorOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace armarkerdetector
{
class ArMarkerdetectorImpl;
} /* armarkerdetector */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::armarkerdetector::ArMarkerdetectorImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
namespace module
{
namespace armarkerdetector
{
class ArThing;
} /* armarkerdetector */
} /* module */
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace armarkerdetector
{

class ArMarkerdetectorImpl : public OpenCVFilterImpl, public virtual ArMarkerdetector, public virtual ArMarkerdetectorOpenCVImpl
{

public:

  ArMarkerdetectorImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~ArMarkerdetectorImpl () {};

  void enableAugmentation (bool enable);
  void enableMarkerCountEvents (bool enable);
  void enableTickEvents (bool enable);
  void setArThing (const std::vector<std::shared_ptr<ArThing>> &arThing);
  void setMarkerPoseFrequency (bool enable, float frequency);
  void setMarkerPoseFrameFrequency (bool enable, int frequency);
  void setPose (int id, int type, float value);
  // TODO: Kludge, because ArMarkerdetectorOpenCVImpl is not inherited from Med\
  iaObject (?)
  virtual std::shared_ptr<MediaObject> getSharedFromThis() { 
    return shared_from_this(); 
  }

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* armarkerdetector */
} /* module */
} /* kurento */

#endif /*  __AR_MARKERDETECTOR_IMPL_HPP__ */
